#
# This file contains configuration flags to customize your site
#

# About/contact
author:
  name:              Pavel Nasovich
  url:               https://twitter.com/forcewake
  email:             forcewake@gmail.com

# Setup
title:               forcewake's blog
tagline:             The Moderately Enthusiastic Programmer
description:         ''
url:                 http://forcewake.me
paginate:            5
baseurl:             ''

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/1325702?v=3&s=460

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: forcewake
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: forcewake
  stackoverflow: users/2688578/pavel-nosovich # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: forcewake

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-58396828-2

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: 1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

prose:
  rooturl: '_posts'
  siteurl: 'http://forcewake.me'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'